---

- name: "Ensure the namespace {{ name }} exists"
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ name }}"
        labels:
          name: "{{ name }}"