---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: homeconnect-etl
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: homeconnect-etl
        template:
          metadata:
            labels:
              app: homeconnect-etl
          spec:
            containers:
              - name: homeconnect-etl-oven
                image: registry.fovodohovi.nl/minimal-footprint:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["minimal_footprint.integrations.homeconnect.run_etl", "SIEMENS-HM876G0B6-68A40E8DFAFD"]
                env: "{{ container_env_variables }}"
              - name: homeconnect-etl-dishwasher
                image: registry.fovodohovi.nl/minimal-footprint:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["minimal_footprint.integrations.homeconnect.run_etl", "012090386871006546"]
                env: "{{ container_env_variables }}"
            imagePullSecrets:
            - name: image-pull-secret
