---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: homeconnect-etl
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: homeconnect-etl
        template:
          metadata:
            labels:
              app: homeconnect-etl
          spec:
            containers:
              - name: homeconnect-etl-oven
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.api2bronze.homeconnect.run", "SIEMENS-HM876G0B6-68A40E8DFAFD"]
                env:
                  - name: PYTHONUNBUFFERED
                    value: "1"
                  - name: CLIENT_ID
                    value: "{{ homeconnect_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ homeconnect_client_secret }}"
                  - name: REDIRECT_URI
                    value: "{{ homeconnect_redirect_uri }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "homeconnect"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "homeconnect"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
              - name: homeconnect-etl-dishwasher
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.api2bronze.homeconnect.run", "012090386871006546"]
                env:
                  - name: PYTHONUNBUFFERED
                    value: "1"
                  - name: CLIENT_ID
                    value: "{{ homeconnect_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ homeconnect_client_secret }}"
                  - name: REDIRECT_URI
                    value: "{{ homeconnect_redirect_uri }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "homeconnect"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "homeconnect"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret
