---
# This playbook prints a simple debug message
- name: Install Docker engine
  hosts: raspberry_pi_4
  become: yes
  gather_facts: True

  tasks:
  - name: apt-get update && apt-get upgrade
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install required packages for DNS server
    apt:
      name:
        - dnsmasq

  - name: Install required packages for Docker
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - apt-transport-https

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
      state: present

  - name: Install Docker Engine
    apt:
      name:
        - docker
        - docker-compose
      update_cache: yes

  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Enable github so that we can clone from it
    shell: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
