---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tibber-etl
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: tibber-etl
        template:
          metadata:
            labels:
              app: tibber-etl
          spec:
            containers:
              - name: tibber-etl-a2b
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.api2bronze.tibber.run_etl"]
                env:
                  - name: API_TOKEN
                    value: "{{ tibber_api_token }}"
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "tibber"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
              # - name: tibber-stream-a2b
              #   image: registry.fovodohovi.nl/enlighted-backend:latest
              #   imagePullPolicy: Always
              #   command: ["python", "-m"]
              #   args: ["enlighted.pipelines.api2bronze.tibber.run_stream"]
              #   env:
              #     - name: API_TOKEN
              #       value: "{{ tibber_api_token }}"
              #     - name: BRONZE_DB_USERNAME
              #       value: "{{ db_username }}"
              #     - name: BRONZE_DB_PASSWORD
              #       value: "{{ db_password }}"
              #     - name: BRONZE_DB_DATABASE
              #       value: "1_bronze"
              #     - name: BRONZE_DB_SCHEMA
              #       value: "tibber"
              #     - name: BRONZE_DB_HOSTNAME
              #       value: "{{ db_hostname }}"
              #     - name: BRONZE_DB_PORT
              #       value: "{{ db_port }}"
              - name: tibber-etl-b2s-consumption
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.bronze2silver.tibber.run", "consumption"]
                env:
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "tibber"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
                  - name: SILVER_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: SILVER_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: SILVER_DB_DATABASE
                    value: "2_silver"
                  - name: SILVER_DB_SCHEMA
                    value: "silver"
                  - name: SILVER_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: SILVER_DB_PORT
                    value: "{{ db_port }}"
              - name: tibber-etl-b2s-production
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.bronze2silver.tibber.run", "production"]
                env:
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "tibber"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
                  - name: SILVER_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: SILVER_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: SILVER_DB_DATABASE
                    value: "2_silver"
                  - name: SILVER_DB_SCHEMA
                    value: "silver"
                  - name: SILVER_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: SILVER_DB_PORT
                    value: "{{ db_port }}"
              # - name: tibber-etl-b2s-live-measurements
              #   image: registry.fovodohovi.nl/enlighted-backend:latest
              #   imagePullPolicy: Always
              #   command: ["python", "-m"]
              #   args: ["enlighted.pipelines.bronze2silver.tibber.run", "live_measurements"]
              #   env:
              #     - name: BRONZE_DB_USERNAME
              #       value: "{{ db_username }}"
              #     - name: BRONZE_DB_PASSWORD
              #       value: "{{ db_password }}"
              #     - name: BRONZE_DB_DATABASE
              #       value: "1_bronze"
              #     - name: BRONZE_DB_SCHEMA
              #       value: "tibber"
              #     - name: BRONZE_DB_HOSTNAME
              #       value: "{{ db_hostname }}"
              #     - name: BRONZE_DB_PORT
              #       value: "{{ db_port }}"
              #     - name: SILVER_DB_USERNAME
              #       value: "{{ db_username }}"
              #     - name: SILVER_DB_PASSWORD
              #       value: "{{ db_password }}"
              #     - name: SILVER_DB_DATABASE
              #       value: "2_silver"
              #     - name: SILVER_DB_SCHEMA
              #       value: "silver"
              #     - name: SILVER_DB_HOSTNAME
              #       value: "{{ db_hostname }}"
              #     - name: SILVER_DB_PORT
              #       value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret
