---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: enlighted-etl
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: enlighted-etl
        template:
          metadata:
            labels:
              app: enlighted-etl
          spec:
            containers:
              - name: enlighted-etl-s2g-heating
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.silver2gold.heating.run"]
                env:
                  - name: SILVER_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: SILVER_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: SILVER_DB_DATABASE
                    value: "2_silver"
                  - name: SILVER_DB_SCHEMA
                    value: "silver"
                  - name: SILVER_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: SILVER_DB_PORT
                    value: "{{ db_port }}"
                  - name: GOLD_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: GOLD_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: GOLD_DB_DATABASE
                    value: "3_gold"
                  - name: GOLD_DB_SCHEMA
                    value: "gold"
                  - name: GOLD_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: GOLD_DB_PORT
                    value: "{{ db_port }}"
              - name: enlighted-etl-s2g-energy-consumption-model
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.silver2gold.energy.energy_consumption_model"]
                env:
                  - name: SILVER_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: SILVER_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: SILVER_DB_DATABASE
                    value: "2_silver"
                  - name: SILVER_DB_SCHEMA
                    value: "silver"
                  - name: SILVER_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: SILVER_DB_PORT
                    value: "{{ db_port }}"
                  - name: GOLD_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: GOLD_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: GOLD_DB_DATABASE
                    value: "3_gold"
                  - name: GOLD_DB_SCHEMA
                    value: "gold"
                  - name: GOLD_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: GOLD_DB_PORT
                    value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret
