---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: enlighted-app
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: enlighted-app
        template:
          metadata:
            labels:
              app: enlighted-app
          spec:
            containers:
              - name: enlighted-app
                image: registry.fovodohovi.nl/enlighted-frontend:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
            imagePullSecrets:
            - name: image-pull-secret

- include_role:
    name: kubernetes/service
  vars:
    namespace: "{{ kubernetes_namespace }}"
    name: enlighted-app
    clusterIP: "{{ cluster_ip_enlighted_app }}"
    targetPort: 80
