---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: enphase-etl
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: enphase-etl
        template:
          metadata:
            labels:
              app: enphase-etl
          spec:
            containers:
              - name: enphase-etl
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.api2bronze.enphase.run"]
                env:
                  - name: PYTHONUNBUFFERED
                    value: "1"
                  - name: API_TOKEN
                    value: "{{ enphase_envoy_api_token }}"
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "enphase"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret
