---

- name: Enable cgroup in /boot/cmdline.txt
  replace:
      path: /boot/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"

- name: Ensure swap is disabled on the server
  block:
    - name: Check whether a package called dphys-swapfile is installed
      package_facts:
        manager: auto

    - name: Turn off "dphys-swapfile" if it exists
      command: dphys-swapfile swapoff
      when: "'dphys-swapfile' in ansible_facts.packages"

    - name: Uninstall "dphys-swapfile" if it exists
      command: dphys-swapfile uninstall
      when: "'dphys-swapfile' in ansible_facts.packages"

    - name: Remove and purge "dphys-swapfile" package if it exists
      apt:
        pkg: dphys-swapfile
        state: absent
        purge: yes
        autoclean: yes
        autoremove: yes
      when: "'dphys-swapfile' in ansible_facts.packages"

- name: Forward IPv4 and let iptables see bridged traffic
  block:
    - name: Load kernel module overlay
      modprobe:
        name: overlay
        state: present
        persistent: present

    - name: Load kernel module br_netfilter
      modprobe:
        name: br_netfilter
        state: present
        persistent: present

    - name: Change various sysctl-settings
      sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
        reload: yes
      with_dict:
        net.ipv4.ip_forward: 1
        net.ipv4.conf.all.forwarding: 1
        net.ipv6.conf.all.forwarding: 1