- name: "Ensure the service {{ name }} exists"
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      spec:
        type: ClusterIP
        clusterIP: "{{ clusterIP }}"
        selector:
          app: "{{ name }}"
        ports:
        - protocol: TCP
          port: 80
          targetPort: "{{ targetPort }}"