---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nibe-auth
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nibe-auth
        template:
          metadata:
            labels:
              app: nibe-auth
          spec:
            containers:
              - name: nibe-auth-api
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.oauth2.nibe.run_api"]
                env:
                  - name: PYTHONUNBUFFERED
                    value: "1"
                  - name: CLIENT_ID
                    value: "{{ nibe_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ nibe_client_secret }}"
                  - name: REDIRECT_URI
                    value: "{{ nibe_redirect_uri }}"
                  - name: SYSTEM_ID
                    value: "{{ nibe_system_id }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "nibe"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
                ports:
                  - containerPort: 80
              - name: nibe-auth-agent
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.oauth2.nibe.run_auth_agent"]
                env:
                  - name: PYTHONUNBUFFERED
                    value: "1"
                  - name: CLIENT_ID
                    value: "{{ nibe_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ nibe_client_secret }}"
                  - name: REDIRECT_URI
                    value: "{{ nibe_redirect_uri }}"
                  - name: SYSTEM_ID
                    value: "{{ nibe_system_id }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "nibe"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret

- include_role:
    name: kubernetes/service
  vars:
    namespace: "{{ kubernetes_namespace }}"
    name: nibe-auth
    clusterIP: "{{ cluster_ip_nibe }}"
    targetPort: 80
