---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nibe-etl
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nibe-etl
        template:
          metadata:
            labels:
              app: nibe-etl
          spec:
            containers:
              - name: nibe-etl-auth-agent
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.oauth2.nibe.run_auth_agent"]
                env:
                  - name: CLIENT_ID
                    value: "{{ nibe_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ nibe_client_secret }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "nibe"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
              - name: nibe-etl-a2b
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.api2bronze.nibe.run"]
                env:
                  - name: CLIENT_ID
                    value: "{{ nibe_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ nibe_client_secret }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "nibe"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
                  - name: DEVICE_ID
                    value: "{{ nibe_device_id }}"
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "nibe"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
              - name: nibe-etl-b2s
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.pipelines.bronze2silver.nibe.run"]
                env:
                  - name: BRONZE_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: BRONZE_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: BRONZE_DB_DATABASE
                    value: "1_bronze"
                  - name: BRONZE_DB_SCHEMA
                    value: "nibe"
                  - name: BRONZE_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: BRONZE_DB_PORT
                    value: "{{ db_port }}"
                  - name: SILVER_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: SILVER_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: SILVER_DB_DATABASE
                    value: "2_silver"
                  - name: SILVER_DB_SCHEMA
                    value: "silver"
                  - name: SILVER_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: SILVER_DB_PORT
                    value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret
