---

- name: Ensure the deployment exists
  kubernetes.core.k8s:
    state: present
    apply: yes
    force: yes
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: netatmo-auth
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: netatmo-auth
        template:
          metadata:
            labels:
              app: netatmo-auth
          spec:
            containers:
              - name: netatmo-auth-api
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.oauth2.netatmo.run_api"]
                env:
                  - name: PYTHONUNBUFFERED
                    value: "1"
                  - name: CLIENT_ID
                    value: "{{ netatmo_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ netatmo_client_secret }}"
                  - name: REDIRECT_URI
                    value: "{{ netatmo_redirect_uri }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "netatmo"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
                ports:
                  - containerPort: 80
              - name: netatmo-auth-agent
                image: registry.fovodohovi.nl/enlighted-backend:latest
                imagePullPolicy: Always
                command: ["python", "-m"]
                args: ["enlighted.oauth2.netatmo.run_auth_agent"]
                env:
                  - name: CLIENT_ID
                    value: "{{ netatmo_client_id }}"
                  - name: CLIENT_SECRET
                    value: "{{ netatmo_client_secret }}"
                  - name: REDIRECT_URI
                    value: "{{ netatmo_redirect_uri }}"
                  - name: AUTH_DB_USERNAME
                    value: "{{ db_username }}"
                  - name: AUTH_DB_PASSWORD
                    value: "{{ db_password }}"
                  - name: AUTH_DB_DATABASE
                    value: "auth"
                  - name: AUTH_DB_SCHEMA
                    value: "netatmo"
                  - name: AUTH_DB_HOSTNAME
                    value: "{{ db_hostname }}"
                  - name: AUTH_DB_PORT
                    value: "{{ db_port }}"
            imagePullSecrets:
            - name: image-pull-secret

- include_role:
    name: kubernetes/service
  vars:
    namespace: "{{ kubernetes_namespace }}"
    name: netatmo-auth
    clusterIP: "{{ cluster_ip_netatmo }}"
    targetPort: 80
