# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 0.0.0.0/0

# Text to speech
tts:
  - platform: google_translate